name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    container: node:latest
    network_mode: service:ui
    services:
      ui:
        image: 'feelmax/fea_ui'
        ports:
          - 3000:3000
      api:
        image: 'feelmax/fea_api'
        ports:
          - 3001:3001
      db:
        image: 'feelmax/fea_db'
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
