name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    services:
      db:
        image: 'mongo'
        ports:
          - 27017:27017
      api:
        image: 'feelmax/fea_api'
        ports:
          - 3001:3001
      ui:
        image: 'feelmax/fea_ui'
        ports:
          - 3000:3000
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Check Running Containers (Debugging)
      run: |
        echo "=== Listing running containers ==="
        docker ps -a
        echo "=== DB SERVICE LOGS ==="
        docker logs $(docker ps -aq --filter "ancestor=db") || true
        echo "=== API SERVICE LOGS ==="
        docker logs $(docker ps -aq --filter "ancestor=feelmax/fea_api") || true
        echo "=== UI SERVICE LOGS ==="
        docker logs $(docker ps -aq --filter "ancestor=feelmax/fea_ui") || true
    - name: Wait for UI to be Ready
      run: |
        echo "Waiting for UI..."
        for i in {1..30}; do
          curl -sSf http://localhost:3000/ && break
          echo "UI is not ready yet. Retrying..."
          sleep 2
        done
    - name: Run Playwright tests
      env:
        UI_URL: http://localhost:3000
        API_URL: http://localhost:3001
      run: |
        echo "Using UI service at $UI_URL"
        echo "Using API service at $API_URL"
        npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30